on:
  push:
    paths: ["packages/gh-page/**/*"]

jobs:
  deploy-gh-page:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          cd packages/gh-page
          npm ci
          yarn

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
