on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: yarn
        run: yarn

      - name: lerna bootstrap
        run: yarn bootstrap

      - name: tame-your-theme/css-style-declaration test
        run: yarn css-style-declaration test

      - name: tame-your-theme/scss test
        run: yarn scss test

  version:
    name: Version
    runs-on: ubuntu-latest
    needs: test
    if: github.event.pull_request.merged == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Version"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          npx lerna version --conventional-commits --conventional-graduate --yes
