
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: yarn 
        run: yarn
        
      - name: lerna bootstrap
        run: yarn bootstrap

      - name: Run a multi-line script
        run: yarn css-style-declaration test
