on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yarn
        run: yarn install --frozen-lockfile
      - name: lerna bootstrap
        run: yarn bootstrap
      - name: tame-your-theme/css-style-declaration test
        run: yarn css-style-declaration test
      - name: tame-your-theme/scss test
        run: yarn scss test

  publish:
    name: publishing
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: "publish"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.TYT_PT }}
        run: |
          git config user.name "${{ github.actor }}"
          npx lerna version --conventional-commits --conventional-graduate --yes
          npx lerna publish from-git --yes --no-verify-access --ignore-scripts
